#!/usr/bin/env ruby

require './rackservice'

require 'minitest/spec'
require 'minitest/autorun'
require 'net/http'
require 'rack'
require 'stringio'

LOG = StringIO.new

class TestAPI < RackService::API
  def initialize
    @log = Logger.new(LOG)
    @log.formatter = RackService::LogFormatter
  end
  def log(msg)
    LOG.reopen
    @log.info msg
    LOG.rewind
  end
  private :log
  def get(param, name:nil)
    response = "get #{param} #{name}"
    log response
    response
  end
  post
  def post(param, name:nil)
    response = "post #{param} #{name}"
    log response
    response
  end
end

describe RackService do
  PORT = 4560
  before do
    @server = Thread.new{ Rack::Server.start(Port:PORT,app:RackService::App.new(TestAPI.new)) }
    loop { @server.join(0); break if (Net::HTTP.get_response('localhost', '/', PORT) rescue nil) }
  end
  it "can get" do
    http = Net::HTTP.new('localhost', PORT)
    req = Net::HTTP::Get.new('/get/param?name=value')
    res = http.request(req)
    LOG.read.must_match /get param value\n$/
    res.body.must_equal "get param value"
  end
  it "can post" do
    http = Net::HTTP.new('localhost', PORT)
    req = Net::HTTP::Post.new('/post/param')
    req.set_form_data({'name'=>'value'})
    res = http.request(req)
    LOG.read.must_match /post param value\n$/
    res.body.must_equal "post param value"
  end
end
